spring:
  security:
    user:
      name:
      password: 
  application:
    name: server
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: ${PORT}
  servlet:
    context-path: /api/v1



