spring:
  security:
    user:
      name:
      password: 
  application:
    name: server
  datasource:
    url: ${DB_URL}
    driver-class-name: ${DRIVER_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASS}
  jpa:
    properties:
      hibernate.dialect: ${DIALECT}
      ddl-auto: update
      show-sql: true

server:
  port: 6969
  servlet:
    context-path: /api/v1



