spring:
  security:
    user:
      name:
      password: 
  application:
    name: server
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=CongNgheJavaLibrary;encrypt=true;trustServerCertificate=true"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Tansang990
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 6969

springdoc:
  api-docs:
    path: /api/v1/api-docs
    enabled: true
  swagger-ui:
    path: /api/v1/api-docs
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    displayRequestDuration: true
    docExpansion: none
    defaultModelsExpandDepth: -1
    defaultModelExpandDepth: 3
  show-actuator: false
  packages-to-scan: com.nhom678.server
  paths-to-match: /api/**
openapi:
  service:
    api-docs: public-api
    title: My API Title
    version: 1.0.0
    server: http://localhost:6969


