spring:
  security:
    user:
      name:
      password: 
  application:
    name: server
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=CongNgheJavaLibrary;encrypt=true;trustServerCertificate=true"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Tansang990
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      show-sql: true

server:
  port: 6969
  servlet:
    context-path: /api/v1



