spring:
  application:
    name: server
  datasource:
    url: "jdbc:sqlserver://localhost:1433;databaseName=CongNgheJavaLibrary;encrypt=true;trustServerCertificate=true"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Tansang990
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
server:
  port: 6969

springdoc:
  api-docs:
    path: /api/v1/docs
  swagger-ui:
    path: /api/v1/docs
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0