spring.application.name=server
server.port=6969


#db config
spring.datasource.url="jdbc:sqlserver://localhost:1433/CongNgheJavaLibrary"
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

