services:
  mysql:
    image: mysql:9.3.0
    container_name: huit-library-container
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_DATABASE: DB-HUIT-LIBRARY
    ports:
      - "3310:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./HUIT-LIBRARY.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - HUIT-LIBRARY-network

  java-app:
    image: eclipse-temurin:17-jdk-alpine
    container_name: java_app_container
    working_dir: /app
    volumes:
      - ./:/app
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - mysql
      - redis
    networks:
      - HUIT-LIBRARY-network

  redis:
    image: redis:7.0-alpine
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - HUIT-LIBRARY-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_library
    restart: always
    depends_on:
      - mysql
    ports:
      - "100:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
    networks:
      - HUIT-LIBRARY-network

networks:
  HUIT-LIBRARY-network:
    name: HUIT-LIBRARY
    driver: bridge

volumes:
  db-data:
  redis-data: